-- TB_FORMA_PAGAMENTO
CREATE TABLE TB_FORMA_PAGAMENTO (
    ID_FORMA_PAGAMENTO BIGINT AUTO_INCREMENT PRIMARY KEY,
    METODO_PAGAMENTO VARCHAR(255) NOT NULL,
    BANDEIRA_CARTAO VARCHAR(255),
    QUANTIDADE_PARCELAS INT NOT NULL
);

-- TB_ANALISE_PAGAMENTO
CREATE TABLE TB_ANALISE_PAGAMENTO (
    ID_ANALISE_PAGAMENTO BIGINT AUTO_INCREMENT PRIMARY KEY,
    VALOR NUMERIC(38, 2) NOT NULL,
    NUMERO_TENTATIVA INT NOT NULL,
    SITUACAO VARCHAR(50) NOT NULL,
    DATA_CRIACAO TIMESTAMP NOT NULL,
    DATA_ATUALIZACAO TIMESTAMP,
    ID_PEDIDO BIGINT NOT NULL,
    ID_FORMA_PAGAMENTO BIGINT NOT NULL,
    CONSTRAINT FK_ANALISE_PAGAMENTO_FORMA_PAGAMENTO FOREIGN KEY (ID_FORMA_PAGAMENTO) REFERENCES TB_FORMA_PAGAMENTO(ID_FORMA_PAGAMENTO)
);

-- TB_PAGAMENTO_APROVADO
CREATE TABLE TB_PAGAMENTO_APROVADO (
    ID_PAGAMENTO_APROVADO BIGINT AUTO_INCREMENT PRIMARY KEY,
    ID_PAGAMENTO VARCHAR(255) NOT NULL,
    DATA_APROVACAO TIMESTAMP NOT NULL,
    ID_ANALISE_PAGAMENTO BIGINT NOT NULL,
    CONSTRAINT FK_PAGAMENTO_APROVADO_ANALISE_PAGAMENTO FOREIGN KEY (ID_ANALISE_PAGAMENTO) REFERENCES TB_ANALISE_PAGAMENTO(ID_ANALISE_PAGAMENTO)
);

-- TB_EVENTO_OUTBOX
CREATE TABLE TB_EVENTO_OUTBOX (
    ID_EVENTO_OUTBOX BIGINT AUTO_INCREMENT PRIMARY KEY,
    TIPO_EVENTO VARCHAR(50) NOT NULL,
    TIPO_AGREGADO VARCHAR(255) NOT NULL,
    ID_AGREGADO VARCHAR(255) NOT NULL,
    PAYLOAD CLOB NOT NULL,
    SITUACAO VARCHAR(50) NOT NULL,
    DATA_CRIACAO TIMESTAMP NOT NULL,
    DATA_ATUALIZACAO TIMESTAMP
);