-- TB_PRODUTO
CREATE TABLE TB_PRODUTO (
    ID_PRODUTO BIGINT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    VALOR NUMERIC(38, 2) NOT NULL,
    QUANTIDADE_DISPONIVEL NUMERIC(38, 2) NOT NULL
);

-- TB_RESERVA_ESTOQUE
CREATE TABLE TB_RESERVA_ESTOQUE (
    ID_RESERVA_ESTOQUE BIGINT AUTO_INCREMENT PRIMARY KEY,
    SITUACAO VARCHAR(50) NOT NULL,
    DATA_CRIACAO TIMESTAMP NOT NULL,
    DATA_ATUALIZACAO TIMESTAMP,
    ID_PEDIDO BIGINT NOT NULL
);

-- TB_PRODUTO_RESERVA_ESTOQUE
CREATE TABLE TB_PRODUTO_RESERVA_ESTOQUE (
    ID_PRODUTO_RESERVA_ESTOQUE BIGINT AUTO_INCREMENT PRIMARY KEY,
    QUANTIDADE_RESERVADA NUMERIC(38, 2) NOT NULL,
    ID_PRODUTO BIGINT NOT NULL,
    ID_RESERVA_ESTOQUE BIGINT NOT NULL,
    CONSTRAINT FK_PRODUTO_RESERVA_ESTOQUE_PRODUTO FOREIGN KEY (ID_PRODUTO) REFERENCES TB_PRODUTO(ID_PRODUTO),
    CONSTRAINT FK_PRODUTO_RESERVA_ESTOQUE_RESERVA_ESTOQUE FOREIGN KEY (ID_RESERVA_ESTOQUE) REFERENCES TB_RESERVA_ESTOQUE(ID_RESERVA_ESTOQUE)
);

-- TB_EVENTO_OUTBOX
CREATE TABLE TB_EVENTO_OUTBOX (
    ID_EVENTO_OUTBOX BIGINT AUTO_INCREMENT PRIMARY KEY,
    TIPO_EVENTO VARCHAR(50) NOT NULL,
    TIPO_AGREGADO VARCHAR(255) NOT NULL,
    ID_AGREGADO VARCHAR(255) NOT NULL,
    PAYLOAD CLOB NOT NULL,
    SITUACAO VARCHAR(50) NOT NULL,
    DATA_CRIACAO TIMESTAMP NOT NULL,
    DATA_ATUALIZACAO TIMESTAMP
);

-- TB_MOVIMENTACAO_ESTOQUE
CREATE TABLE TB_MOVIMENTACAO_ESTOQUE (
    ID_MOVIMENTACAO_ESTOQUE BIGINT AUTO_INCREMENT PRIMARY KEY,
    TIPO VARCHAR(50) NOT NULL,
    OBSERVACAO VARCHAR(255),
    SITUACAO VARCHAR(50) NOT NULL,
    DATA_CRIACAO TIMESTAMP NOT NULL,
    DATA_ATUALIZACAO TIMESTAMP,
    ID_RESERVA_ESTOQUE BIGINT,
    CONSTRAINT FK_MOVIMENTACAO_ESTOQUE_RESERVA_ESTOQUE FOREIGN KEY (ID_RESERVA_ESTOQUE) REFERENCES TB_RESERVA_ESTOQUE(ID_RESERVA_ESTOQUE)
);

-- TB_PRODUTO_MOVIMENTACAO_ESTOQUE
CREATE TABLE TB_PRODUTO_MOVIMENTACAO_ESTOQUE (
    ID_PRODUTO_MOVIMENTACAO_ESTOQUE BIGINT AUTO_INCREMENT PRIMARY KEY,
    QUANTIDADE NUMERIC(38, 2) NOT NULL,
    ID_PRODUTO BIGINT NOT NULL,
    ID_MOVIMENTACAO_ESTOQUE BIGINT NOT NULL,
    CONSTRAINT FK_PRODUTO_MOVIMENTACAO_ESTOQUE_PRODUTO FOREIGN KEY (ID_PRODUTO) REFERENCES TB_PRODUTO(ID_PRODUTO),
    CONSTRAINT FK_PRODUTO_MOVIMENTACAO_ESTOQUE_MOVIMENTACAO_ESTOQUE FOREIGN KEY (ID_MOVIMENTACAO_ESTOQUE) REFERENCES TB_MOVIMENTACAO_ESTOQUE(ID_MOVIMENTACAO_ESTOQUE)
);
