-- TB_PEDIDO
CREATE TABLE TB_PEDIDO (
    ID_PEDIDO BIGINT AUTO_INCREMENT PRIMARY KEY,
    VALOR_SUBTOTAL NUMERIC(38, 2) NOT NULL,
    VALOR_DESCONTO NUMERIC(38, 2),
    VALOR_TOTAL NUMERIC(38, 2) NOT NULL,
    ID_CLIENTE BIGINT NOT NULL,
    CPF_CLIENTE VARCHAR(255) NOT NULL,
    NOME_CLIENTE VARCHAR(255) NOT NULL,
    EMAIL_CLIENTE VARCHAR(255) NOT NULL,
    SITUACAO VARCHAR(50) NOT NULL,
    DATA_CRIACAO TIMESTAMP NOT NULL,
    DATA_ATUALIZACAO TIMESTAMP
);

-- TB_PRODUTO_PEDIDO
CREATE TABLE TB_PRODUTO_PEDIDO (
    ID_PRODUTO_PEDIDO BIGINT AUTO_INCREMENT PRIMARY KEY,
    QUANTIDADE NUMERIC(38, 2),
    VALOR_UNITARIO NUMERIC(38, 2),
    VALOR_TOTAL NUMERIC(38, 2),
    ID_PRODUTO BIGINT NOT NULL,
    NOME_PRODUTO VARCHAR(255) NOT NULL,
    ID_PEDIDO BIGINT NOT NULL,
    CONSTRAINT FK_PRODUTO_PEDIDO_PEDIDO FOREIGN KEY (ID_PEDIDO) REFERENCES TB_PEDIDO(ID_PEDIDO)
);

-- TB_EVENTO_OUTBOX
CREATE TABLE TB_EVENTO_OUTBOX (
    ID_EVENTO_OUTBOX BIGINT AUTO_INCREMENT PRIMARY KEY,
    TIPO_EVENTO VARCHAR(50) NOT NULL,
    TIPO_AGREGADO VARCHAR(255) NOT NULL,
    ID_AGREGADO VARCHAR(255) NOT NULL,
    PAYLOAD CLOB NOT NULL,
    SITUACAO VARCHAR(50) NOT NULL,
    DATA_CRIACAO TIMESTAMP NOT NULL,
    DATA_ATUALIZACAO TIMESTAMP
);




