-- TB_USUARIO
CREATE TABLE TB_USUARIO (
    ID_USUARIO BIGINT AUTO_INCREMENT PRIMARY KEY,
    CPF VARCHAR(255) NOT NULL,
    SENHA VARCHAR(255) NOT NULL,
    NOME_COMPLETO VARCHAR(255) NOT NULL
);

-- TB_CLIENTE
CREATE TABLE TB_CLIENTE (
    ID_CLIENTE BIGINT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    CPF VARCHAR(255) NOT NULL,
    SITUACAO VARCHAR(50) NOT NULL
);

-- TB_PRODUTO
CREATE TABLE TB_PRODUTO (
    ID_PRODUTO BIGINT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    VALOR NUMERIC(38, 2) NOT NULL,
    SITUACAO VARCHAR(50) NOT NULL
);

-- TB_VENDA
CREATE TABLE TB_VENDA (
    ID_VENDA BIGINT AUTO_INCREMENT PRIMARY KEY,
    DATA_EMISSAO TIMESTAMP NOT NULL,
    VALOR_TOTAL NUMERIC(38, 2) NOT NULL,
    DATA_CRIACAO TIMESTAMP NOT NULL,
    DATA_ATUALIZACAO TIMESTAMP,
    ID_CLIENTE BIGINT NOT NULL,
    CONSTRAINT FK_VENDA_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES TB_CLIENTE(ID_CLIENTE)
);

-- TB_PRODUTO_VENDA
CREATE TABLE TB_PRODUTO_VENDA (
    ID_PRODUTO_VENDA BIGINT AUTO_INCREMENT PRIMARY KEY,
    QUANTIDADE NUMERIC(38, 2),
    VALOR_UNITARIO NUMERIC(38, 2),
    VALOR_TOTAL NUMERIC(38, 2),
    ID_PRODUTO BIGINT,
    ID_VENDA BIGINT,
    CONSTRAINT FK_PRODUTO_VENDA_PRODUTO FOREIGN KEY (ID_PRODUTO) REFERENCES TB_PRODUTO(ID_PRODUTO),
    CONSTRAINT FK_PRODUTO_VENDA_VENDA FOREIGN KEY (ID_VENDA) REFERENCES TB_VENDA(ID_VENDA)
);